# Build and deploy to GitHub Pages using SvelteKit static adapter
# For more information see: https://kit.svelte.dev/docs/adapter-static

name: Build and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# Allow only one concurrent deployment; cancel in-progress runs for the same branch
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          VITE_GIT_COMMIT_REF: ${{ steps.vars.outputs.sha_short }}
        run: npm run gh-pages-build
      - name: Setup Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
  deploy:
    if: github.event_name == 'push'
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
